server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: true

logging:
  level:
    '[com.example.moduleadmin]': DEBUG
    '[org.hibernate.type]': TRACE